MODEL:
  MODEL_NAME: "FastSurferCNN"
  NUM_CLASSES: 2
  LOSS_FUNC: "combined"
  NUM_FILTERS: 64
  NUM_FILTERS_INTERPOL: 32
  NUM_CHANNELS: 7
  KERNEL_H: 3
  KERNEL_W: 3
  KERNEL_C: 1
  STRIDE_CONV: 1
  STRIDE_POOL: 2
  POOL: 2
  HEIGHT: 256
  WIDTH: 256
  BASE_RES: 1.0
  INTERPOLATION_MODE: "bilinear"
  CROP_POSITION: "top_left"
  OUT_TENSOR_WIDTH: 256
  OUT_TENSOR_HEIGHT: 256

TRAIN:
  BATCH_SIZE: 8
  LOG_INTERVAL: 10
  RESUME: false
  RESUME_EXPR_NUM: "Default"
  NUM_EPOCHS: 70
  NUM_STEPS: 10
  FINE_TUNE: false
  CHECKPOINT_PERIOD: 2
  NUM_WORKERS: 1

TEST:
  BATCH_SIZE: 8

DATA:
  PATH_HDF5_TRAIN: "/localmount/volume-ssd/users/uline/fastCNN_split/coronal/train_coronal.hdf5"
  PATH_HDF5_VAL: "/localmount/volume-ssd/users/uline/fastCNN_split/coronal/val_coronal.hdf5"
  PLANE: "coronal"

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true

OPTIMIZER:
  BASE_LR: 0.01
  LR_SCHEDULER: "cosineWarmRestarts"
  GAMMA: 0.3
  STEP_SIZE: 5
  ETA_MIN: 0.0001
  T_ZERO: 10
  T_MULT: 2
  MOMENTUM: 0.90
  DAMPENING: 0.0
  NESTEROV: true
  WEIGHT_DECAY: 0.0001
  OPTIMIZING_METHOD: "adamW"

NUM_GPUS: 1
LOG_DIR: "FastSurferCNN"
EXPR_NUM: "FastSurferCNN_coronal"
RNG_SEED: 1
SUMMARY_PATH: "FastSurferCNN/summary/FastsurferCNN_coronal"
CONFIG_LOG_PATH: "FastSurferCNN/config/FastsurferCNN_coronal"