MODEL:
  MODEL_NAME: "FastSurferCNN"
  NUM_CLASSES: 2
  LOSS_FUNC: "combined"
  NUM_FILTERS: 64
  NUM_FILTERS_INTERPOL: 32
  NUM_CHANNELS: 7
  KERNEL_H: 3
  KERNEL_W: 3
  KERNEL_C: 1
  STRIDE_CONV: 1
  STRIDE_POOL: 2
  POOL: 2
  HEIGHT: 256
  WIDTH: 256
  BASE_RES: 1.0
  INTERPOLATION_MODE: "bilinear"
  CROP_POSITION: "top_left"
  OUT_TENSOR_WIDTH: 256
  OUT_TENSOR_HEIGHT: 256

TRAIN:
  BATCH_SIZE: 16
  LOG_INTERVAL: 50
  RESUME: false
  RESUME_EXPR_NUM: "Default"
  NUM_EPOCHS: 70
  NUM_STEPS: 10
  FINE_TUNE: false
  CHECKPOINT_PERIOD: 2
  NUM_WORKERS: 1

TEST:
  BATCH_SIZE: 16

DATA:
  PATH_HDF5_TRAIN: "/localmount/volume-hd/users/uline/fastCNN_split/axial/train_axial.hdf5"
  PATH_HDF5_VAL: "/localmount/volume-hd/users/uline/fastCNN_split/axial/val_axial.hdf5"
  PLANE: "axial"

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true

OPTIMIZER:
  BASE_LR: 0.01
  LR_SCHEDULER: "step_lr"
  GAMMA: 0.95
  STEP_SIZE: 5
  ETA_MIN: 0.0001
  T_ZERO: 10
  T_MULT: 2
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: true
  WEIGHT_DECAY: 0.0001
  OPTIMIZING_METHOD: "adam"

NUM_GPUS: 1
LOG_DIR: "FastsurferCNN"
EXPR_NUM: "FastSurferCNN_axial"
RNG_SEED: 1
SUMMARY_PATH: "FastSurferVINN/summary/FastsurferCNN_axial"
CONFIG_LOG_PATH: "FastSurferVINN/config/FastsurferCNN_axial"