MODEL:
  MODEL_NAME: "FastSurferUNET"
  NUM_CLASSES: 2
  LOSS_FUNC: "combined"
  NUM_FILTERS: 64
  NUM_FILTERS2: 64
  NUM_FILTERS_INTERPOL: 32
  NUM_CHANNELS: 7
  KERNEL_H: 3
  KERNEL_W: 3
  KERNEL_C: 1
  STRIDE_CONV: 1
  STRIDE_POOL: 2
  POOL: 2
  HEIGHT: 256
  WIDTH: 256
  BASE_RES: 1.0
  INTERPOLATION_MODE: "bilinear"
  CROP_POSITION: "top_left"
  OUT_TENSOR_WIDTH: 256
  OUT_TENSOR_HEIGHT: 256


TRAIN:
  BATCH_SIZE: 2
  LOG_INTERVAL: 10
  RESUME: True
  RESUME_EXPR_NUM: "FastSurferUNET_coronal"
  NUM_EPOCHS: 30
  NUM_STEPS: 10
  FINE_TUNE: True
  CHECKPOINT_PERIOD: 2
  NUM_WORKERS: 1

TEST:
  BATCH_SIZE: 2

DATA:
  PATH_HDF5_TRAIN: "/localmount/volume-ssd/users/uline/fastCNN_split/coronal/train_coronal.hdf5"
  PATH_HDF5_VAL: "/localmount/volume-ssd/users/uline/fastCNN_split/coronal/val_coronal.hdf5"
  PLANE: "coronal"

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true

OPTIMIZER:
  OPTIMIZING_METHOD : 'adamW'
  WEIGHT_DECAY : 1e-4
  BASE_LR : 0.05
  GAMMA: 0.1
  LR_SCHEDULER : 'multiStep'
  MILESTONE: [70]
  MOMENTUM : 0.95

NUM_GPUS: 1
LOG_DIR: "FastSurferUNET"
EXPR_NUM: "FastSurferUNET_coronal"
RNG_SEED: 1
SUMMARY_PATH: "FastSurferUNET/summary/FastsurferUNET_coronal"
CONFIG_LOG_PATH: "FastSurferUNET/config/FastsurferUNET_coronal"